const express = require("express")
const khabarnameController = require("../controllers/Khabarname_controller")
const upload = require("../middwlwares/khabarname_middelware")
const authOrizationToken = require("../middwlwares/auth_middelware")
const adminAuthOrization = require("../middwlwares/admin_middelware")
const router = express.Router()
router.get("/api/khabarname",khabarnameController.getAll)
router.post("/khabarname",authOrizationToken,adminAuthOrization,upload.fields([{name:"image" , maxCount:1}]),khabarnameController.addInfo)
router.put("/api/putkhabarname/:id",authOrizationToken,adminAuthOrization,upload.fields([{name:"image" , maxCount:1}]),khabarnameController.updateInfo)
router.delete("/api/deletekhabarname/:id",authOrizationToken,adminAuthOrization,khabarnameController.deleteInfo)
module.exports = router