const express = require("express")
const podcastController = require("../controllers/podcast_contriller")
const upload = require("../middwlwares/podcast_middelware")
const authOrizationToken = require("../middwlwares/auth_middelware")
const adminAuthOrization = require("../middwlwares/admin_middelware")
const router = express.Router()
router.get("/",podcastController.getAll)
router.post("/",authOrizationToken,adminAuthOrization,upload.fields([{ name: "audio", maxCount: 1 },{ name: "cover", maxCount: 1 }]),podcastController.addInfo)
router.put("/:id",authOrizationToken,adminAuthOrization,upload.fields([{ name: "audio", maxCount: 1 },{ name: "cover", maxCount: 1 }]),podcastController.updateInfo)
router.delete("/:id",authOrizationToken,adminAuthOrization,podcastController.deleteInfo)
module.exports = router